name = "astro-chiri"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-10-03"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true